apiVersion: v1
kind: Service
metadata:
  name: flan-t5-small-mlserver-http
  labels:
    serving.kserve.io/inferenceservice: flan-t5-small-mlserver
spec:
  type: ClusterIP
  selector:
    app: isvc.flan-t5-small-mlserver-predictor
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
